#!/bin/bash
# Written by Paul Phan <paul@mrpaulphan.com>

clear
echo -e "Setup"
echo -e "\t" "Install/Update dependencies"


# Setup

# Check to see if user has node

hey() {
  # Check node version
  node=$( node -v )
  substring="."

  if [[ "$node" =~ "$substring" ]]; then
      echo "'$node' contains '$substring'";
  else
      echo "Please install Node.js and rerun this script";
  fi

  npm=$( npm -v )
  if [[ "$npm" =~ "$substring" ]]; then
    echo -e "\t Updating npm dependencies..."
      npm install
  else
      echo "Please install Node.js and rerun this script";
  fi

}

test() {
  echo -e "test"
}

export -f test


ask() {
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        read -p "$1 [$prompt] " REPLY </dev/tty
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

asks() {

  # node
  if [ -f "package.json" ]; then
    if [ -f "node_modules" ]; then
        echo -e "\t Installing npm dependencies..."
        npm install
    else
        if ask "Would you like to update your npm dependencies?"; then
            echo -e "\t Updating npm dependencies..."
            npm update
        fi
    fi
  fi

  # bower
  if [ -f "bower.json" ]; then
    if [ -f "node_modules" ]; then
        echo -e "\t Installing bower dependencies..."
        bower install
    else
        if ask "Would you like to update your bower dependencies?"; then
            echo -e "\t Updating bower dependencies..."
            bower update
        fi
    fi
  fi
  echo ''



}
